//
//  QingChunServerAPIs.h
//  QingChunApp
//
//  Created by Peter Lee on 15/1/26.
//  Copyright (c) 2015年 Peter Lee. All rights reserved.
//

#import <Foundation/Foundation.h>

//FOUNDATION_EXTERN NSString *const QCD_BASE_URL_STRING_IOS;
//FOUNDATION_EXTERN NSString *const QCD_LOGIN_SESSION_DATA_IOS;

//FOUNDATION_EXTERN NSString *const QCD_MESSAGE_PATH_STRING_IOS;

//FOUNDATION_EXTERN NSString *const QCD_CHECK_SUM_SECRET_STRING_IOS;

//注册方法路劲
FOUNDATION_EXTERN NSString *const QCD_REGISTER_PATH_STRING_IOS;

//邮箱登陆的路径
FOUNDATION_EXTERN NSString *const QCD_LOGIN_2_PATH_STRING_IOS;

//读取青春风铃的消息的路径
FOUNDATION_EXTERN NSString *const QCD_BELL_NUMBER_PATH_STRING_IOS;

//赞、踩、收藏
FOUNDATION_EXTERN NSString *const QCD_MSG_ACTION_PATH_STRING_IOS;

//读取评论
FOUNDATION_EXTERN NSString *const QCD_MSG_READ_COMMENT_PATH_STRING_IOS;
// 增加评论
FOUNDATION_EXTERN NSString *const QCD_MSG_ADD_COMMENT_PATH_STRING_IOS;

//上传图片路径
FOUNDATION_EXTERN NSString *const QCD_MSG_UPLOAD_IMAGE_PATH_STRING_IOS;

//发表说说路径
FOUNDATION_EXTERN NSString *const QCD_MSG_PUBLISH_PATH_STRING_IOS;